# ─── Common Taps ──────────────────────────────────────────────────────────────
tap "jenkins-zh/jcli"
tap "lusingander/tap"

# ─── Common Brews (cross-platform) ───────────────────────────────────────────
brew "awscli"
brew "bat"
brew "btop"
brew "colima"
brew "cryptography"
brew "docker"
brew "docker-buildx"
brew "duckdb"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git-delta"
brew "gitui"
brew "go"
brew "golangci-lint"
brew "graphviz"
brew "htop"
brew "imagemagick"
brew "jp"
brew "jpeg-xl"
brew "jq"
brew "jsonlint"
brew "lazydocker"
brew "lazygit"
brew "libraw"
brew "librsvg"
brew "libxmlsec1"
brew "luacheck"
brew "markdownlint-cli"
brew "mpv"
brew "mycli"
brew "ncurses"
brew "neovim"
brew "nmap"
brew "node"
brew "nvm"
brew "oath-toolkit"
brew "ollama", restart_service: :changed
brew "openapi-generator"
brew "opentofu"
brew "pandoc"
brew "podman"
brew "pass"
brew "pass-otp"
brew "pgcli"
brew "pinentry"
brew "pipx"
brew "poppler"
brew "pre-commit"
brew "protobuf"
brew "pyenv"
brew "python@3.13"
brew "rain"
brew "ranger"
brew "ripgrep"
brew "shellcheck"
brew "stow"
brew "tig"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "unbound"
brew "uv"
brew "w3m"
brew "watch"
brew "websocat"
brew "wget"
brew "yamllint"
brew "ykman"
brew "zbar"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "jenkins-zh/jcli/jcli"
brew "lusingander/tap/stu"

# ─── Go Packages (cross-platform) ────────────────────────────────────────────
go "github.com/Clever/csvlint/cmd/csvlint"
go "github.com/ethereum/go-ethereum/cmd/abigen"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/go-swagger/go-swagger/cmd/swagger"
go "github.com/google/wire/cmd/wire"
go "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen"
go "github.com/securego/gosec/v2/cmd/gosec"
go "golang.org/x/tools/gopls"
go "google.golang.org/protobuf/cmd/protoc-gen-go"
go "honnef.co/go/tools/cmd/staticcheck"

# ─── macOS Only ───────────────────────────────────────────────────────────────
if OS.mac?
  tap "jorgelbg/tap"
  tap "ngrok/ngrok"
  tap "steipete/tap"
  tap "teamookla/speedtest"
  tap "yakitrak/yakitrak"

  brew "hadolint"
  brew "kubernetes-cli"
  brew "mas"
  brew "openjdk@17"
  brew "openjdk@21"
  brew "openssh"
  brew "pinentry-mac"
  brew "pngpaste"
  brew "postgresql@14"
  brew "qemu"
  brew "rancher-cli"
  brew "telnet"
  brew "terraform-docs"
  brew "tesseract"
  brew "tflint"
  brew "yarn"
  brew "yt-dlp"
  brew "jorgelbg/tap/pinentry-touchid"
  brew "steipete/tap/remindctl"
  brew "yakitrak/yakitrak/obsidian-cli"
  brew "teamookla/speedtest/speedtest"

  cask "beyond-compare"
  cask "chatgpt-atlas"
  cask "claude"
  cask "codex"
  cask "cursor"
  cask "dbeaver-community"
  cask "font-fira-code-nerd-font"
  cask "font-hack-nerd-font"
  cask "font-jetbrains-mono-nerd-font"
  cask "fork"
  cask "ghostty"
  cask "google-chrome"
  cask "intellij-idea-ce"
  cask "iterm2"
  cask "itsycal"
  cask "mitmproxy"
  cask "ngrok/ngrok/ngrok"
  cask "obsidian"
  cask "openemu"
  cask "postman"
  cask "redis-insight"
  cask "sequel-ace"
  cask "session-manager-plugin"
  cask "slack"
  cask "steam"
  cask "visual-studio-code"
  cask "whatsapp"
  cask "windsurf"
  cask "xbar"
  cask "zed"
  cask "zoom"

  mas "Amphetamine", id: 937984704
  mas "Telegram", id: 747648890
  mas "Monosnap", id: 540348655
  mas "Numbers", id: 409203825
  mas "Windows App", id: 1295203466
end

# ─── Linux Only ───────────────────────────────────────────────────────────────
if OS.linux?
  flatpak "com.google.Chrome"
  flatpak "org.telegram.desktop"
  flatpak "dev.zed.Zed"
end
